# Once done this will define
#  GVis_FOUND
#  GVis_INCLUDE_DIRS
#  GVis_LIBRARIES
#

set(GVis_INCLUDE_DIRS)
set(GVis_LIBRARIES optimized GVis debug GVisd)

find_package(OpenGL REQUIRED)
list(APPEND GVis_INCLUDE_DIRS ${OPENGL_INCLUDE_DIR})
list(APPEND GVis_LIBRARIES ${OPENGL_LIBRARIES})

find_package(GLEW REQUIRED)
list(APPEND GVis_INCLUDE_DIRS ${GLEW_INCLUDE_DIR})
list(APPEND GVis_LIBRARIES ${GLEW_LIBRARIES})

find_package(GLFW REQUIRED)
list(APPEND GVis_INCLUDE_DIRS ${GLFW_INCLUDE_DIR})
list(APPEND GVis_LIBRARIES ${GLFW_LIBRARIES})

find_package(GLM REQUIRED)
list(APPEND GVis_INCLUDE_DIRS ${GLM_INCLUDE_DIR})

set(GVis_FOUND "YES")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GVis DEFAULT_MSG GVis_INCLUDE_DIRS GVis_LIBRARIES)